Fixed the Zeronet
YunoHost-Apps/zeronet_ynh pull request #15
Opened 2021-02-08 20:14 UTC by anmol26s

Fixed Zeronet to work again.

2021-02-08 20:18 UTC, ericgaspar commented
!testme

2021-02-08 20:19 UTC, ericgaspar requested changes

2021-02-08 20:19 UTC, ericgaspar commented on README.md
> +[![Integration level](https://dash.yunohost.org/integration/zeronet.svg)](https://dash.yunohost.org/appci/app/zeronet) ![](https://ci-apps.yunohost.org/ci/badges/zeronet.status.svg) ![](https://ci-ap
```suggestion
[![Integration level](https://dash.yunohost.org/integration/zeronet.svg)](https://dash.yunohost.org/appci/app/zeronet) ![](https://ci-apps.yunohost.org/ci/badges/zeronet.status.svg) ![](https://ci-apps.yunohost.org/ci/badges/zeronet.maintain.svg)  
```

2021-02-09 14:51 UTC, anmol26s commented
!testme

2021-02-09 16:36 UTC, merged