Yuno break fix
YunoHost-Apps/zeronet_ynh pull request #22
Opened 2021-05-23 06:21 UTC by anmol26s

## Problem
- *Package remove python3-gevent-websocket and python3-gevent thus breaking YunoHost*

## Solution
- *Add packages in dependencies*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

2021-05-23 06:24 UTC, anmol26s commented
!testme

2021-05-23 17:06 UTC, anmol26s commented
!testme

2021-05-24 09:47 UTC, yalh76 requested changes

2021-05-24 09:47 UTC, yalh76 commented on scripts/install
> +ynh_install_app_dependencies $pkg_dependencies
Would be better to keep that in the `INSTALL DEPENDENCIES` step

2021-05-24 09:47 UTC, yalh76 commented on scripts/install
> +pip3 install merkletools PySocks websocket_client gevent-ws coincurve bencode
Why not directly using the requirements from `requirements.txt`

2021-05-24 09:47 UTC, yalh76 commented on scripts/remove
> +pip3 uninstall -y  merkletools PySocks coincurve maxminddb bencode
Not sure it's a good idea to remove them if they are use by other apps or YunoHost

2021-05-24 09:47 UTC, yalh76 commented on scripts/restore
> +pip3 install  merkletools PySocks websocket_client gevent-ws coincurve bencode
Why not directly using the requirements from `requirements.txt`

2021-05-24 09:47 UTC, yalh76 commented on scripts/upgrade
> +pip3 install  merkletools PySocks websocket_client gevent-ws coincurve bencode
Why not directly using the requirements from `requirements.txt`

2021-05-24 10:07 UTC, yalh76 commented
!testme

2021-05-24 10:17 UTC, anmol26s commented
`Would be better to keep that in the INSTALL DEPENDENCIES step`
Its because that the requirement package do not mess with Yunohost dependencies. Installing from pip can break the Yunohost.
Some packages need to be secured through dependency helper so that Yunohost don't break.  
See this https://forum.yunohost.org/t/attributeerror-module-moulinette-interfaces-has-no-attribute-api/15724

And if additional dependencies come in we need to install it with pip anyways. 
https://forum.yunohost.org/t/zeronet-decentralized-websites/2584/8?u=kanhu


`Not sure it's a good idea to remove them if they are use by other apps or YunoHost`
Why keep the packages, when its not required by any app? Maybe by chance some apps uses it, app can be forced upgraded. 
Is there better way to check if the package is required by other app ?

2021-05-24 10:58 UTC, yalh76 commented
> 
> 
> `Would be better to keep that in the INSTALL DEPENDENCIES step`
> Its because that the requirement package do not mess with Yunohost dependencies. Installing from pip can break the Yunohost.
> Some packages need to be secured through dependency helper so that Yunohost don't break.
> See this https://forum.yunohost.org/t/attributeerror-module-moulinette-interfaces-has-no-attribute-api/15724

I agree with that but there is no difference between keeping it in it's own step `INSTALL DEPENDENCIES` like in example_ynh or having it in `BUILDING ZERONET`. For example during upgrade you didn't move the line `ynh_install_app_dependencies $pkg_dependencies`

> 
> And if additional dependencies come in we need to install it with pip anyways.
> https://forum.yunohost.org/t/zeronet-decentralized-websites/2584/8?u=kanhu
> 
> `Not sure it's a good idea to remove them if they are use by other apps or YunoHost`
> Why keep the packages, when its not required by any app? Maybe by chance some apps uses it, app can be forced upgraded.
> Is there better way to check if the package is required by other app ?

I don't know if there is a better way to check if python package are use somewhere but I think it's better to have unsued package than breaking other apps ...

2021-05-24 12:06 UTC, anmol26s commented
Ok, so till we implement better way to handle python dependencies we can have any solution which don't break Yunohost.
Closing this.

2021-05-24 12:06 UTC, closed without merging